### ISSUE TITLE
Script doesn't work on client.

### ISSUE THREAD

**Issue by tonnguyen1310** [Detergent13/tft-bot#101]
first of all thank you very much for writing this script!
The script works perfectly for me ingame-wise, but failed to queue up/ re-queue after surrender. I tried to follow the instruction to hit ok when in a TFT lobby but nothing happened and I had to queqe up manually. I don't see any other issues addressing this problem so I'm thinking the problem is on my side. Do you maybe have any idea why it doesn't work for me?

Thank you

**Comment by RomeoAlphaEkko** [comment]
Do you mean you get back to Home ?

where there is now the jinx rocket instead of the post game lobby?

**Comment by tonnguyen1310** [comment]
I meant when the script successfully surrenders it'll return me to the client and then the scoreboard appears, without queuing up again. Same with queuing for the first time, all the actions in the client have to be done manually by me. But in a game the script still works (picking 1st unit, buying units, surrender after krugs ect.) It's so weird.

**Comment by RomeoAlphaEkko** [comment]
What resolution is the league client

**Comment by tonnguyen1310** [comment]
it's 1280x720 as default

**Comment by RomeoAlphaEkko** [comment]
Could you try recapturing the confirmation button

**Comment by tonnguyen1310** [comment]
this did the trick for me, thank you very much!
