### ISSUE TITLE
Bot works to start a queue and accept, but once in game it doesn't do anyting.

### ISSUE THREAD

**Issue by Megurami** [Detergent13/tft-bot#102]
Hello, 

I read all previous issues before making this. I got the bot successfully installed, once I hit OK in a tft lobby, it successfully prompts a queue and accepts the match. Once I am in the game however nothing happens. The bot doesnt buy any characters or anything. And the tft.py box only shoes "Bot started, queuing up!" and never changes.
Any help would be very appreciated! Thank you so much.

**Comment by Detergent13** [comment]
Try recapturing the loading screen maybe?

**Comment by Megurami** [comment]
Thanks that seemed to work! However, now it does everything correctly except it doesn't surrender.
