### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by hyp0711** [Detergent13/tft-bot#104]
I installed it according to the instructions, but even if I press ok in the tft lobby, the program turns off immediately
Is there a solution?
Press the "확인" button on the screen in the picture to turn off the program immediately.
![3](https://user-images.githubusercontent.com/103652793/206862869-e0239f4b-4bbe-4094-b72b-69777de9d139.PNG)

**Comment by RomeoAlphaEkko** [comment]
Ah, you first want to move to the folder you have the requirements file in

Like cd: <paste path from explorer> -enter
Now so the requirements command

**Comment by hyp0711** [comment]
Thank you. As you said, it works.
Is it possible to set it to a language other than English without any problem?

**Comment by RomeoAlphaEkko** [comment]
- language no, you would have to re screenshot all the buttons as they click surrender noch the French word for it

- you surrender at a certain stage not minutes
- you can change it in the file directly

**Comment by hyp0711** [comment]
Could you tell me where to fix it?

**Comment by hyp0711** [comment]
Also, if I die within the changed period, do I automatically play the game again?

**Comment by RomeoAlphaEkko** [comment]
# change this if you want to ...

**Comment by RomeoAlphaEkko** [comment]
That is the comment behind the line where you have to change the image name

**Comment by RomeoAlphaEkko** [comment]
> Also, if I die within the changed period, do I automatically play the game again?

Yes

**Comment by hyp0711** [comment]
I'm sorry, but I'm not good at programming, so could you tell me exactly which file to modify?

**Comment by RomeoAlphaEkko** [comment]
> I'm sorry, but I'm not good at programming, so could you tell me exactly which file to modify?

TFT.py

Me neither the start / setup was not that easy but then it was smooth sailing

**Comment by hyp0711** [comment]
![4](https://user-images.githubusercontent.com/103652793/206865242-468006cb-f2f6-46ca-9991-c1fef6485950.PNG)
Is this the image comment you mentioned?

**Comment by RomeoAlphaEkko** [comment]
You can change the 3-1.png to any of the stages you have files for

**Comment by hyp0711** [comment]
Are you saying that I should replace the 3-1 photo file with 6-6?

**Comment by RomeoAlphaEkko** [comment]
No within the TFT.py file you have to change the code

**Comment by hyp0711** [comment]
TFT.py file does not open Is there a way to open it?

**Comment by hyp0711** [comment]
![3](https://user-images.githubusercontent.com/103652793/206866772-74738875-1f15-4752-849f-48acf10d4ddf.PNG)
Is it right to change it like this?

**Comment by Detergent13** [comment]
Yes, that should work!
