### ISSUE TITLE
Bot not requeuing

### ISSUE THREAD

**Issue by hyp0711** [Detergent13/tft-bot#107]
After the second round is over, you can't match the next game by moving to the fast game lobby, not the tft lobby.
Someone else posted the same question, but I didn't understand the solution.
Please explain in detail.

**Comment by Detergent13** [comment]
Sorry, not sure if I understand fully. Could you elaborate?

**Comment by Detergent13** [comment]
Are you referring to #94 perhaps?

**Comment by hyp0711** [comment]
Yes, that’s right.
It's a question that you tagged

**Comment by hyp0711** [comment]
I'm leaving a question because I don't understand the answer to the question you tagged.

**Comment by hyp0711** [comment]
Can you fix it?

**Comment by hyp0711** [comment]
Thank you. I would appreciate it if you could revise it as soon as possible.

**Comment by hyp0711** [comment]
Where should I set it up?

**Comment by Detergent13** [comment]
Enable "close client during game" in  client settings.

**Comment by hyp0711** [comment]
Will the problem be solved by just turning off the client all the time?

**Comment by Detergent13** [comment]
Yes, that's what I've been saying and what the other issue has been saying. 

I'll eventually make a fix so that this setting doesn't need to be on.

**Comment by hyp0711** [comment]
Thank you.
