### ISSUE TITLE
Which language should I set, French or English, for this to work?

### ISSUE THREAD

**Issue by hyp0711** [Detergent13/tft-bot#108]
Which language should I set, French or English, for this to work?

**Comment by hyp0711** [comment]
Which language should I set, French or English, for this to work?

**Comment by Detergent13** [comment]
English. Although if you want to, you can take new photos (in the captures folder) in any language.

**Comment by hyp0711** [comment]
Lol Do you mean to set the language of the game in English?

**Comment by RomeoAlphaEkko** [comment]
You need ingame and launcher in English
