### ISSUE TITLE
Code Idea for "skip waiting for stats"

### ISSUE THREAD

**Issue by RomeoAlphaEkko** [Detergent13/tft-bot#109]
new:

`def end_match():
    while not onscreen("./captures/find match ready.png"):  # added a main loop for the end match function to ensure you make it to the find match button.
        while onscreen("./captures/missions ok.png"):
            click_to("./captures/missions ok.png")
            time.sleep(2)
        while onscreen("./captures/skip waiting for stats.png"):
            click_to("./captures/skip waiting for stats.png")
            time.sleep(5)
        while onscreen("./captures/play again.png"):
            click_to("./captures/play again.png")
        while onscreen("./captures/play.png"):
            click_to("./captures/play.png")
            time.sleep(5)
        while onscreen("./captures/confirm.png"):
            click_to("./captures/confirm.png")
            time.sleep(5)`

old:
`def end_match():
    while not onscreen("./captures/find match ready.png"):  # added a main loop for the end match function to ensure you make it to the find match button.
        while onscreen("./captures/missions ok.png"):
            click_to("./captures/missions ok.png")
            time.sleep(2)
        while onscreen("./captures/skip waiting for stats.png"):
            click_to("./captures/skip waiting for stats.png")
            time.sleep(5)
        while onscreen("./captures/play again.png"):
            click_to("./captures/play again.png")
            `

soe the changes are at the end: 
`        while onscreen("./captures/play.png"):
            click_to("./captures/play.png")
            time.sleep(5)
        while onscreen("./captures/confirm.png"):
            click_to("./captures/confirm.png")
            time.sleep(5)`

the needed immages are: 

![play](https://user-images.githubusercontent.com/89660477/207134633-d3d01341-ad1f-4c47-a7f0-089f1e469ccf.PNG)
![confirm](https://user-images.githubusercontent.com/89660477/207134635-99e048b9-46bf-4237-ae35-12b6f9411175.PNG)

**Comment by Detergent13** [comment]
Thank you! Could you make this a Pull Request so that it's easier to merge and you get credit?

**Comment by RomeoAlphaEkko** [comment]
Should be able to within the next days

**Comment by Detergent13** [comment]
Sounds good, no rush :)

**Comment by RomeoAlphaEkko** [comment]
#112
