### ISSUE TITLE
Doesn't Work With Garena

### ISSUE THREAD

**Issue by RadioactivePeaches** [Detergent13/tft-bot#11]
garena is a seperate client, even though this is a pixel bot it doesn't seem to work, It says it's started the queue but it hasn't.

**Comment by Detergent13** [comment]
That's interesting, from my understanding it should work fine out of the box, but you should be able to just re-capture the images to get it working. I can't really add this to the main branch since it'd risk breaking everything aside from Garena, but happy to move it to a branch if you do end up fixing it yourself!

**Comment by Detergent13** [comment]
Might just be an issue with captures overall- I'll test later today. (see #12)

**Comment by RadioactivePeaches** [comment]
I recaptured [find match ready.png] but it wouldn't queue up either.

**Comment by Detergent13** [comment]
Try re-capturing the TFT logo as well- it won't try to find the match unless it sees that in the lobby as well. If that doesn't work, I'll take a look when I'm home and roll out a fix regardless!

**Comment by RadioactivePeaches** [comment]
tried doing that as well, I think it needs to be looked at by someone who knows what they're doing lol I don't understand why it thinks it's working

**Comment by Detergent13** [comment]
Working fine for me still- I'll think about it and get back to you. Just to
get the obvious out of the way- you're running it on the correct
resolution/on your main monitor right?

**Comment by RadioactivePeaches** [comment]
I messed with the resolution, the cursor moves to click find match.. and then doesn't click it. I queue myself, and decline the match, the script starts working. It drags the cursor to the find match button, clicks it, but doesn't press accept when popup appears.

**Comment by Detergent13** [comment]
Might be an issue of it clicking off of the hitbox of the button, or maybe lacking permissions to actually click? I'd try re-capturing the find match button/accept match buttons with a tighter view of the button, just to make sure it doesn't miss. Also, what OS are you using?

**Comment by RadioactivePeaches** [comment]
Windows. I was trying to figure out how to run it as admin but idk how to. I'll try recapturing

**Comment by Detergent13** [comment]
Personally I just have a .bat file set up that's just:

`py tft.py
pause`

Then you can set it to run as admin in the properties of the batch file. Not sure if there's a better way to do it, but works for me ¯\_(ツ)_/¯

**Comment by Detergent13** [comment]
Closing since the author seems to have disappeared. Will re-open if help is still needed.
