### ISSUE TITLE
About the captured version

### ISSUE THREAD

**Issue by hyp0711** [Detergent13/tft-bot#111]
I wanted to play in Korean, so I replaced all the captured copies in the file with Korean server captured copies, but it didn't work.
To be exact, I accept the game, but it doesn't work within the in-game

**Comment by hyp0711** [comment]
The existing capture file was a png file, so I used a png file to change it
Compared to the Korean server, we used the correct captured version.
Does the picture have to be the same size?

**Comment by RomeoAlphaEkko** [comment]
at which part does it stop working, like:

post the lines from the cmd to see if we even get into the game

**Comment by hyp0711** [comment]
The program accepts the game, but it doesn't work when you enter the game.
It seems that the cmd says "Loading".

**Comment by RomeoAlphaEkko** [comment]
are the rounds numbered 1-1 ?

**Comment by hyp0711** [comment]
no

**Comment by hyp0711** [comment]
![h](https://user-images.githubusercontent.com/103652793/207730105-a6ac18d6-1e89-41d1-996c-91cecd6fd055.PNG)

**Comment by hyp0711** [comment]
It only works up to here with cmd

**Comment by RomeoAlphaEkko** [comment]
If the rounds are written in Korean you have to capture them too

**Comment by CaS1ow** [comment]
매크로 개발에 참여중인 한국인입니다
캡쳐는 본인에 해상도에 맞게끔 캡쳐하셔서 사용하시면됩니다
