### ISSUE TITLE
The bot won't surrender

### ISSUE THREAD

**Issue by Fbwndgus** [Detergent13/tft-bot#114]
The bot doesn't surrender and doesn't leave even after the game

**Comment by RomeoAlphaEkko** [comment]
Hi,
1. has it worked before?
2. how long have you been using it?
3. could you give us a copy of the content of the cmd window?
4. is it working at all ingame, like running in the carussel, using the shop? etc?

**Comment by Detergent13** [comment]
Please re-capture everything to do with surrendering (your surrender stage, surrender 1 & 2, settings)

Also please ensure you're following the other common troubleshooting steps listed!

**Comment by Fbwndgus** [comment]
If you use a bot, the bot responds to "find match" and "accept", but nothing else responds. Is this a matter of capture?

**Comment by Fbwndgus** [comment]
1

**Comment by Detergent13** [comment]
Ah. Sounds like you should recapture loading.png then.

**Comment by RomeoAlphaEkko** [comment]
And in which resolution does your game window run in and which mode, full screen?

**Comment by Fbwndgus** [comment]
1280x 720 and full screen

**Comment by Fbwndgus** [comment]
I captured it and tried again, but it still doesn't work when I enter the game

**Comment by Fbwndgus** [comment]
my most pick warwick.... I really want T_T

**Comment by RomeoAlphaEkko** [comment]
That is the double problem

First go borderless

Second the resolution doesn't fit the captured images


Fbwndgus ***@***.***> schrieb am So., 25. Dez. 2022, 05:45:

**Comment by Detergent13** [comment]
@Fbwndgus the correct resolution is in the troubleshooting steps... please actually read them since it does help with a lot of common issues like this one.

If you want to use your resolution instead of 1920x1080, just recapture everything. But it'd be easier to just switch if possible
