### ISSUE TITLE
saying ModuleNotFoundError: No module named 'printy'

### ISSUE THREAD

**Issue by HJS006** [Detergent13/tft-bot#115]

**Comment by HJS006** [comment]
Hi, I tried py "tft.py" then it says what i said in title.

**Comment by RomeoAlphaEkko** [comment]
You installed the requirements?

**Comment by HJS006** [comment]
I think i didn't do that. How to download requirements?

**Comment by RomeoAlphaEkko** [comment]
Plz read the readme file

**Comment by HJS006** [comment]
Ok. I did it now. But it say  pip subprocess to install build dependencies did not run successfully. I dont know well about python. Do you know how to solve it?

**Comment by RomeoAlphaEkko** [comment]
Which version of python did you install?

**Comment by RomeoAlphaEkko** [comment]
It can result in problems, best is to use the version it is tested for
