### ISSUE TITLE
bot doesn't start

### ISSUE THREAD

**Issue by froostiz** [Detergent13/tft-bot#12]
i think captures needs to be updated

**Comment by Detergent13** [comment]
Got it, thanks for the heads up. Haven't had the chance to test recently but should be able to some time today.

**Comment by froostiz** [comment]
i tried it on vm today and bot did queued up and accepted match but did nothing after that

**Comment by Detergent13** [comment]
Probably has to do with resolution- make sure that you're using both resolutions listed in the readme, and re-capture in-game images if not.

**Comment by Detergent13** [comment]
Closing since the author seems to have disappeared. Will re-open if help is still needed.
