### ISSUE TITLE
Find Match button grayed out after a bunch of games

### ISSUE THREAD

**Issue by vancitysekhon** [Detergent13/tft-bot#120]
![image](https://user-images.githubusercontent.com/90118581/228650944-67845428-b835-4a53-9d4b-45443a2d520d.png)
After a bunch of games I get stuck here. No specific amount of games but it always does end up happening.

**Comment by RomeoAlphaEkko** [comment]
One of the client bugs, like the game window not opening

**Comment by RomeoAlphaEkko** [comment]
Btw you are in a SR lobby not tft

**Comment by vancitysekhon** [comment]
![image](https://user-images.githubusercontent.com/90118581/228652167-c1888101-6de7-4936-ab7d-cb98e6fc1068.png) It's a TFT lobby

**Comment by RomeoAlphaEkko** [comment]
could you confirm if this problem is still in 13.7 i have not hit the prior bugs which stopped me before
