### ISSUE TITLE
help! (apologies)

### ISSUE THREAD

**Issue by helpleasesaelpleh** [Detergent13/tft-bot#122]
sorry i have 0 coding knowledge and was wondering if there was a youtube guide or something for the exact steps to be performed
I downloaded python but I don't know how to proceed, not sure what I'm supposed to do for:  "Navigate to your install directory using cd and run pip install -r requirements.txt in Command Prompt. Navigate to your install directory using cd and run py "tft.py" in Command Prompt."
I use a MacBook and I google says Terminal is the mac version of Command Prompt(?)
thank you in advance to any kind soul who responds.... <3

**Comment by Detergent13** [comment]
Yep, Terminal is the equivalent I think. And the commands will be the same!

**Comment by helpleasesaelpleh** [comment]
hi thank you for responding!! i typed "cd </Users/XXX/Downloads/tft-bot-main/tft.py>" but received the response "zsh: parse error near `\n' "
I tried various permutations of the cd as well, like /cd or no <> for the path or something
sorry for the trouble :')

**Comment by Detergent13** [comment]
Try `cd /Users/XXX/Downloads/tft-bot-main/tft.py` (without the <>.)

Normally when you see <> in a command/documentation it sort of means "insert here." Just a tip!

**Comment by helpleasesaelpleh** [comment]
roger! thank u for the advice<3

i tried without <> and it responded with "cd: not a directory: /Users/XXX/Downloads/tft-bot-main/tft.py"

**Comment by Detergent13** [comment]
Oh. Oops! Try

`cd /Users/XXX/Downloads/tft-bot-main`

tft.py is a file, not a directory. The tft-bot-main directory *contains* tft.py

**Comment by helpleasesaelpleh** [comment]
thank you! i did that, and also had to figure out some things (use pip3, redownload python 3.8.3 specifically and not the newest version), and I believe I accomplished the second step?
when i tried to do the third step (py "tft.py") the screenshot is what i got
![Screenshot 2023-04-19 at 4 50 07 PM](https://user-images.githubusercontent.com/130973714/233021836-f472aef2-f7ac-4a01-a984-f6213743eabd.png)

**Comment by Detergent13** [comment]
What's the output of `python -V`?

**Comment by helpleasesaelpleh** [comment]
"Python 2.7.16"!

Which is weird because i deleted and redownloaded Python 3.8.3(?)

**Comment by Detergent13** [comment]
Try `which python` and delete any directories that aren't 3.8.3.

**Comment by helpleasesaelpleh** [comment]
searched it! the unwanted Python 2.7 is in /usr/bin and google told me not to delete it (idk how to delete it either) because it's preinstalled by Apple and without it my MacBook won't run. 

i think to change the Python version I need to download homebrew and another thing to make Terminal run 3.8.3 instead! alternatively I can try running using BootCamp... but I think these steps are a bit of work so I will figure it out after my exams next week! 

thank you for all your help thus far Detergent <3

**Comment by Detergent13** [comment]
Gotcha, you could also try `python3 tft.py`, or using the full filepath of `python` from `which`, i.e. something like `/Users/XXX/abc/xyz/python tft.py`. The `python` command is pretty much just shorthand for this. (Well... currently it's a shortcut for 2.7, but you get the idea)

No problem, let me know if you need anything!
