### ISSUE TITLE
having problems starting the program

### ISSUE THREAD

**Issue by josephisticated** [Detergent13/tft-bot#123]
getting this output with python 3.8.3:

> Bot started, queuing up!
> Traceback (most recent call last):
>   File "tft.py", line 225, in <module>
>     queue()
>   File "tft.py", line 63, in queue
>     if onscreen("./captures/tft logo.png"):
>   File "tft.py", line 26, in onscreen
>     return search(path, precision)[0] != -1
>   File "C:\Users\Yusuf\AppData\Local\Programs\Python\Python38\lib\site-packages\python_imagesearch\imagesearch.py", line 115, in imagesearch
>     im = pyautogui.screenshot()
>   File "C:\Users\Yusuf\AppData\Local\Programs\Python\Python38\lib\site-packages\pyautogui\__init__.py", line 224, in _couldNotImportPyScreeze
>     raise PyAutoGUIException(
> pyautogui.PyAutoGUIException: PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of 
> Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.

downloaded dependencies too

**Comment by Detergent13** [comment]
What's the output of `python -V`? (or `py -V`)

I see you mentioned you installed 3.8.3, but just making sure the correct version is actually running.

**Comment by Detergent13** [comment]
In that case, probably worth deleting your python modules folder and re-installing the requirements.

**Comment by josephisticated** [comment]
cleared the modules' folder and reinstalled default ones, ran `pip install -r requirements.txt` and then tried again but having the same error again.

**Comment by Detergent13** [comment]
My guess would be that you somehow have two different modules directories somehow? Maybe try creating a venv in anaconda if it's convenient for you?

I'm not completely sure though, those two steps should've knocked out most common issues.

If anybody else has experience with a similar issue, please feel free to chime in!

**Comment by Gogoreds** [comment]
Hey Detergent, I'm getting the same error here; _"PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of
Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call."_ 
Tried your suggestions to joseph and still the same, any solutions to this?

**Comment by RomeoAlphaEkko** [comment]
> Tried your suggestions to joseph and still the same, any solutions to this?

Hi,
is it sometimes happening, always?

did u just start using it or have been for a longer time?

**Comment by Gogoreds** [comment]
Hey,

Thanks for replying on a Sunday! I actually just installed it today and ran into the _pyscreeze_ error. But yeah it just never started for me.

**Comment by RomeoAlphaEkko** [comment]
> pyscreeze

if you have a bit of time, we could try some trouble shooting

try switching out def end_match()

def end_match():
    while not onscreen("./captures/find match ready.png"):  # added a main loop for the end match function to ensure you make it to the find match button.
        while onscreen("./captures/missions ok.png"):
            click_to("./captures/missions ok.png")
            time.sleep(2)
        while onscreen("./captures/skip waiting for stats.png"):
            click_to("./captures/skip waiting for stats.png")
            time.sleep(5)
        while onscreen("./captures/play again.png"):
            click_to("./captures/play again.png")
        play()

best to do a copy of the tft.py and change it there then testrun it

**Comment by Gogoreds** [comment]
Yes sir, just booting it up now.

**Comment by RomeoAlphaEkko** [comment]
another test you could do is go to your "cmd" type "pip list" scroll down and check what version your pyscreeze is

**Comment by Gogoreds** [comment]
play() is not defined.

**Comment by RomeoAlphaEkko** [comment]
ups, my bad, we never implemented the screenshot function here.

just delete that try and check ur pyscreeze verison

**Comment by Gogoreds** [comment]
![image](https://github.com/Detergent13/tft-bot/assets/89981448/d3163fff-ceca-4bc7-bc41-84456af12040)

**Comment by RomeoAlphaEkko** [comment]
@Detergent13 you are better at this

some info drop from me
Pillow                    9.0.0
pip                       23.0.1 (could be updated)
PyAutoGUI                 0.9.50
PyScreeze                 0.1.28


https://pillow.readthedocs.io/en/stable/installation.html

**Comment by Gogoreds** [comment]
Is the script running with the these updated versions of packages? Should I just go ahead and change the requirements to these and try again?

**Comment by Detergent13** [comment]
Sorry, I completely forgot to respond to this. That's certainly worth a try! I would also recommend giving a virtual environment such as anaconda a shot- make a new environment with Python 3.8.3, install the requirements, and attempt to run under the environment.

**Comment by sotha-sil-zen** [comment]
https://github.com/Detergent13/tft-bot/issues/126#issuecomment-1657131450

This may help.

**Comment by Detergent13** [comment]
Should be fixed in #138
