### ISSUE TITLE
help pls :)

### ISSUE THREAD

**Issue by liquidsoap1** [Detergent13/tft-bot#124]
I keep getting SyntaxError:invalid when I try to input anything. i dont know what to do :(

**Comment by Detergent13** [comment]
What do you mean by "input anything"?

**Comment by liquidsoap1** [comment]
i installed the tip and everything and when i tryed to install requirement i got syntax error and for evrything i tried i got that error. i have 0 knowledge for coding can u help me

**Comment by liquidsoap1** [comment]
i installed the zip and everything and when i tried to install requirements i got syntax error and for evrything i tried i got that error. i have 0 knowledge for coding can u help me

**Comment by RomeoAlphaEkko** [comment]
```
Installation:
Install Python 3.8.3 from [here](https://www.python.org/downloads/), or the Windows Store
Navigate to your install directory using cd and run pip install -r requirements.txt in Command Prompt
Navigate to your install directory using cd and run py "tft.py" in Command Prompt
Follow the instructions in your terminal window! Get into a TFT lobby, have the created window visible on your screen, and press 'OK' to start the bot!
```



which part did you do and at which part did it fail?

**Comment by liquidsoap1** [comment]
i already installed  python 3.8.3 and tris to run the file but i just got error and thats it. i also dont understand navigate to directory “cd”

**Comment by RomeoAlphaEkko** [comment]
That part is your problem for now

https://www.lifewire.com/change-directories-in-command-prompt-5185508

**Comment by RomeoAlphaEkko** [comment]
Try installing or upgrading pip

https://pip.pypa.io/en/stable/installation/

**Comment by liquidsoap1** [comment]
i just upgraded pip and got the same error.

**Comment by RomeoAlphaEkko** [comment]
btw when installing python did you check the box for path or not?

**Comment by liquidsoap1** [comment]
![pythonn](https://github.com/Detergent13/tft-bot/assets/138173237/52dcc7c8-0060-4759-b825-42c9ff525951)
u reinstalled python and checked that path box and after that cmd installed my requirements but when i tried to run `py tft.py` command i got this error.

**Comment by liquidsoap1** [comment]
i fixed it now

**Comment by liquidsoap1** [comment]
i started the bot and everything is okay but bot did not use items in game

**Comment by RomeoAlphaEkko** [comment]
That is normal aka intended
