### ISSUE TITLE
get's stuck on surrendering

### ISSUE THREAD

**Issue by disembodiment** [Detergent13/tft-bot#127]
as mentioned in the title, will play as normal then when it gets to the part where it tries to surrender it appears to get stuck and never completes the action. (Mouse just freezes and python just says Trying to surrender)

**Comment by RomeoAlphaEkko** [comment]
Hi, let me rerun it in about 7-8 hours

**Comment by RomeoAlphaEkko** [comment]
successful test, recapture the settings button
![settings](https://github.com/Detergent13/tft-bot/assets/89660477/2c281121-1270-405d-8b7f-25356cfa39ae)
