### ISSUE TITLE
Cooperation

### ISSUE THREAD

**Issue by Pompeiro** [Detergent13/tft-bot#13]
Hey, what about working together on TFT bot?

**Comment by Pompeiro** [comment]
@Detergent13 I mean to add new features, upgrade bot to be able to win with oponents on gold ELO. I know thats big words but we could talk on discord and bring some ideas together. I asked you about that because I am burnout and looking for some motivation to work, and I think when someone interested in project would talk with me the motivation will rise higher. Discord Papaj#3719

**Comment by Detergent13** [comment]
Added!
