### ISSUE TITLE
bot queues up and gets into the game but freezes after

### ISSUE THREAD

**Issue by disembodiment** [Detergent13/tft-bot#130]
so when queing up, it will accept get into the game, and then will not do anything afterthat, it will just freeze as if it never actually got into the game. what can be done to fix this?

**Comment by RomeoAlphaEkko** [comment]
Does the chat message loading appear if not update that picture

**Comment by duc23** [comment]
> Does the chat message loading appear if not update that picture

How can I get the new "loading" picture?

**Comment by RomeoAlphaEkko** [comment]
Just screenshot a small part of it and replace it in the folder

**Comment by RomeoAlphaEkko** [comment]
![loading](https://github.com/Detergent13/tft-bot/assets/89660477/ad796fbe-1c15-4ecc-b2ad-635bd660c9d9)
