### ISSUE TITLE
Help needed. Crashes when running.

### ISSUE THREAD

**Issue by DezDez123** [Detergent13/tft-bot#131]
I open the tft lobby and run the program and it crashes as soon as I hit okay. The python window closes and gives no dialog. Looking to trouble shoot the issue. Thank you.

Have checked resolutions are correct. 
Made sure it was running on primary monitor.

**Comment by Detergent13** [comment]
How are you running it? (What OS, through what means, what command, etc)

Without seeing the error message it's pretty much impossible to debug.
