### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Retsiger** [Detergent13/tft-bot#133]
What am i doing wrong?
![obraz_2023-11-01_031750320](https://github.com/Detergent13/tft-bot/assets/75540007/236bdcfd-71de-4658-8b7f-fcb542339226)

**Comment by RomeoAlphaEkko** [comment]
first retry pip install -r requirements.txt

**Comment by Retsiger** [comment]
Still same error :/

**Comment by Retsiger** [comment]
I thought it might be due to the system version (Win 11). However, I get the same error on my work computer (Win 7).
I'm using Python version 3.8.3. I also think that I am following what is described in the installation tab. I will be grateful for any help.

**Comment by 4i7** [comment]
> I thought it might be due to the system version (Win 11). However, I get the same error on my work computer (Win 7). I'm using Python version 3.8.3. I also think that I am following what is described in the installation tab. I will be grateful for any help.

Have you read about the error message PyAutoGUIException?
It describes what is happening immediately afterwards, so you should literally deal with it.
You could try a command like this

pip3 uninstall pyscreeze
pip3 install pyscreeze=0.1.28
