### ISSUE TITLE
Question/Help script stops

### ISSUE THREAD

**Issue by RomeoAlphaEkko** [Detergent13/tft-bot#134]
Hi,
was unsuccessfull with googling.

Testing an update for s10.

As i remembered it worked fine until i ran the last windows updates.

But now the script randomly "stops". it can be after 1 game or multible games.

the command line goes back to C.\Users\...

any1 an idea how to find out why it stopped / to trace back what were the last operations?

**Comment by Detergent13** [comment]
Strange! Is there any error message when it does stop, or just waiting for your next command?

**Comment by RomeoAlphaEkko** [comment]
Stops, it shows the standard command line waiting for a command c:/

My guess at the moment is that the pbe client randomly goes full screen from borderless
