### ISSUE TITLE
little help =D 

### ISSUE THREAD

**Issue by MrIslamAIman** [Detergent13/tft-bot#139]
i have a problem when i run the file it close immediately without any errors 
i checked most of the closed case and still no help 
i will leave here a pic to make sure that i did everything right 

![Screenshot 2024-02-19 143503](https://github.com/Detergent13/tft-bot/assets/16799897/182bc783-7385-416c-aadf-22157d162f31)

**Comment by Detergent13** [comment]
Create a batch (.bat) file with the first line being whatever command you run it with, and the second line being `pause`. 

There's a 99% chance it does give an error, it just closes right after! This stops it.

Let me know what error you get when you do this.

**Comment by MrIslamAIman** [comment]
![Screenshot 2024-02-20 002134](https://github.com/Detergent13/tft-bot/assets/16799897/fd21fe49-0e27-4a78-a916-e14da71f29a4)
need to till u it is a new device with fresh windows

**Comment by Detergent13** [comment]
Try running with `python` instead of `py`... you're checking the version with `python` so that's what I'd expect to work!

**Comment by MrIslamAIman** [comment]
nope didn't work the same result nothing shows 
a hint: when I install the Python I chose  (install for all users ) which makes it installed at (c:\program files) does this make any changes?
and i choose the (path) option too

**Comment by Detergent13** [comment]
Can you run any other Python scripts?

**Comment by MrIslamAIman** [comment]
after checking it was a python problem i uninstall it and install it again and all good =D sorry for all the disturb and thanks for the fast answers
