### ISSUE TITLE
New Patch Released, not working

### ISSUE THREAD

**Issue by buzz0503** [Detergent13/tft-bot#14]
Your bot was working amazingly in last version, but after today's update it seems to be not working. Can you try to fix it and make it usable for the new version of tft?

**Comment by Detergent13** [comment]
Yep, known issue. I'm pretty busy with life at the moment so might be a bit until it's fixed, but it will be eventually. 

If you or anybody else reading this would like to open up a PR and make the changes themselves, please feel free to! Should just be a matter of getting a new early-game comp and taking screenshots for it.

**Comment by Detergent13** [comment]
Just to update you, PR #15 should fix these issues, I just need to find the time to review the code and merge. Feel free to use that branch in the meantime.

**Comment by Detergent13** [comment]
Just merged #15, should be working now!
