### ISSUE TITLE
Riot Vanguard - Project Deprecation

### ISSUE THREAD

**Issue by Detergent13** [Detergent13/tft-bot#140]
There's about a 99% chance that this project will be deprecated when Riot Vanguard rolls out. I'd be shocked if it doesn't detect the bot!
Definitely don't use the bot on any accounts that you care about once it does roll out in your region.

There is still hope for the bot- it wouldn't be too hard to port it to work on the mobile app through an Android emulator. (@PsychoticDragan and I have talked about this.) However I don't really play LoL anymore and am pretty busy with life. We'll see if I work on it. 

In any case, anybody has my blessing to port/modify the code! (As long as it aligns with the license.)

Cheers,
Detergent

**Comment by zhaxxDev** [comment]
I was thinking of some external implementation of this, getting a raspberry pi and streaming the screen state to it, and getting the rpi to send out a spoof mouse input to the computer. In theory this should be undetected. I'll probably get started on this because years ago I bought 300 dollars of RP to grind the battle pass forever.

**Comment by Detergent13** [comment]
Sounds super overkill, but like a really fun project! Let me know if you do get it running. 

I think objectively the easiest way is just to run the TFT mobile app on Bluestacks or similar, and send clicks from outside the emulator. No Vanguard on mobile ;)

**Comment by zhaxxDev** [comment]
From my research it sounds like they are banning everyone using bluestacks :( That would be the easiest method for sure though.

**Comment by akshualy** [comment]
> From my research it sounds like they are banning everyone using bluestacks :( That would be the easiest method for sure though.

Heya, can you add me on Discord (`akshualy`) and provide some links and or ban message screen shots? We (this project's dev and the fork's devs) are currently working on the emulator alternative, so anything you can provide before a release would be appreciated.

**Comment by RomeoAlphaEkko** [comment]
any news on the bluestacks part? sadly google microsoft dropped the android implementation project

**Comment by Detergent13** [comment]
> any news on the bluestacks part? sadly google microsoft dropped the android implementation project

 Currently in development and very promising! (99% thanks to @akshualy) It's using ADB so should be emulator-agnostic and run in the background, which is super cool.

**Comment by RomeoAlphaEkko** [comment]
[Riot Vanguard](https://www.leagueoflegends.com/de-de/news/dev/dev-vanguard-x-lol/) goes life and support for DirectX 9 will be ceased

**Comment by Detergent13** [comment]
Seems like it's time to archive the repo. Thanks to everyone that helped out along the way! If you still want a bot, take a look at the spiritual successor that I've helped develop a little bit. 

https://github.com/TeamFightTacticsBots/Alune
