### ISSUE TITLE
opencv-python==4.2.0.34 non-existent & more

### ISSUE THREAD

**Issue by MrMindBlow** [Detergent13/tft-bot#16]
It did not want to download nor find it in the first place with 4.2.0.34 so I went ahead and changed it to 4.5.1.48 and it installed everything correctly then changed the sum in the tft.py itself to 4.5.1.48 as well and it was ready to launch, till I pressed OK and it just did nothing.

I'm not sure if this is a problem for many or just on my end.

**Comment by VincentVanWolf** [comment]
I ran into the same issue you did, changing the version to 4.5.1.48 in both requirements.txt and tft.py did the trick.

Running the tft.py in cmd with admin privilege starts the bot, however, all it does is que up and accept the match. Nothing else happens beyond that point.

**Comment by MrMindBlow** [comment]
> I ran into the same issue you did, changing the version to 4.5.1.48 in both requirements.txt and tft.py did the trick.
> 
> Running the tft.py in cmd with admin privilege starts the bot, however, all it does is que up and accept the match. Nothing else happens beyond that point.

It did not even Q up for me so yeah.

Thing is busted atm

**Comment by VincentVanWolf** [comment]
In order for it to Q up, in my case that is, I needed to run the python file, then open up the lobby and then press OK while the League of Legends client is in foreground.

I have been trying to resolve other issues, having problems with surrender at the moment, but hoping to have it working soon.

**Comment by Detergent13** [comment]
Hi, it's already been discussed and is a known issue that it's not working with the new set. (#14)

In the meantime, before I have the time to actually review the code (pretty busy at the moment with life), please use PR #15, which seems to be working fine at the moment.
