### ISSUE TITLE
Bot doesn't work past accepting que

### ISSUE THREAD

**Issue by VincentVanWolf** [Detergent13/tft-bot#17]
As the title says, the script runs fine up to the point when it accepts the match.

The last thing CMD shows is "Bot started, queuing up!", which makes me believe that it is probably stuck in a loop, and that it doesn't recognize that it has moved past that point.

**Comment by Detergent13** [comment]
Hi, it's already been discussed and is a known issue that it's not working with the new set. (#14)

In the meantime, before I have the time to actually review the code (pretty busy at the moment with life, please use PR #15, which seems to be working fine at the moment.
