### ISSUE TITLE
Not sure what im doing wrong script opens then closes

### ISSUE THREAD

**Issue by isiink** [Detergent13/tft-bot#19]
Not sure what im doing wrong script opens then closes. Please help me my discord is Zi#9302

**Comment by Detergent13** [comment]
Hi, how are you running the script? And have you taken a look at the common troubleshooting steps?

**Comment by isiink** [comment]
i installed pyhton 3.8.3 as instructed and i tried running the install for pip as well but keep getting syntax error. I also tried opening the tft.py but it closes afterwards not sure what I'm suppose to do

**Comment by Detergent13** [comment]
What's the error for pip? And make sure that you're running from command line, not double clicking the file or anything.

**Comment by Detergent13** [comment]
Closing as author seems to be inactive. Please re-open if you still need help.
