### ISSUE TITLE
program not working

### ISSUE THREAD

**Issue by chrisrao25** [Detergent13/tft-bot#20]
I have finished all the steps as following and press the OK bottom after I created a tft lobby but it didn't work.

**Comment by Detergent13** [comment]
Hi, have you taken a look at common troubleshooting points? This is almost certainly an issue with resolution or you needing to re-capture images.

**Comment by Detergent13** [comment]
Closing as the author seems to be inactive/common and solved issue. Please re-open if you need additional help!
