### ISSUE TITLE
Script queues and accepts but does not buy champs or surrender

### ISSUE THREAD

**Issue by yoimlive777** [Detergent13/tft-bot#21]
I got the script working since it does queue for matches and accept them, however, once in game nothing happens, it just afks until I lose...

It doesn't surrender/buy champs/etc. This is running the game on 1080 like recommended, I also tried making my captures and it still did nothing.

**Comment by Detergent13** [comment]
Hi, have you done every single capture, and what step does your console output get frozen on? My thought is that it's probably not detecting something like `1-1.png` to progress the script, and therefore gets stuck.

**Comment by carloskpo10** [comment]
hand I already corrected it but now it does nothing, it just shows and stays still, it takes almost 7 hours to do it, I left it all night and it has not started any
it tells me that the bot is in queue and does nothing else

**Comment by Detergent13** [comment]
Closing this issue as the original author seems to be inactive. Please re-open if you still need help!
