### ISSUE TITLE
Bot gets confused?

### ISSUE THREAD

**Issue by PsychoticDragan** [Detergent13/tft-bot#22]
I left the bot on and came back to find that only 4 or so games had ran in a 12 hour time frame.  The bot seemed to still think it was in a match. I think that the other players all must have surrendered before the bot would thus leaving it stuck.
![Bot log](https://user-images.githubusercontent.com/85346858/120795103-0d173600-c507-11eb-99e3-c87cf5127e32.PNG)

![image](https://user-images.githubusercontent.com/85346858/120795146-1dc7ac00-c507-11eb-8036-ec04bf5e5004.png)

**Comment by zhaxxDev** [comment]
That happens when everyone surrenders early and you get to first place before the round reaches the surrender point. I fixed that bug in a minor update to the code.

**Comment by Detergent13** [comment]
Thank you @zhaxxDev! Seems like the case. #23 should fix this when merged.

**Comment by Detergent13** [comment]
@PsychoticDragan did #24 fix this? Will close if so.

**Comment by PsychoticDragan** [comment]
I haven't run into the issue again, since updating it. I do seem to get stuck where I assume the bot misses the settings button when trying to surrender which then leaves the bot stuck trying to surrender. This would be a capture issue? As it tends to click on the left corner of the matching image in the client?

**Comment by Detergent13** [comment]
Definitely a capture issue- probably is either narrowly missing the hitbox for the button or not finding the capture altogether. Should work if you just recapture a bit tighter than the current one- feel free to open up a PR for it if you do!

**Comment by zhaxxDev** [comment]
Possible more permanent fix to add a "nudge" to the click on function? Moving the cursor slightly right and down

**Comment by PsychoticDragan** [comment]
I was gonna mention such a possibility but I haven't used python myself. So I wasn't sure if you'd have to just add a like z amount to the x and minus r amount from y to do it or if you could pull the image dimensions and set it to change the clicking coordinates based on the images dimensions to center the click to the center of the location. Albeit the first option would be much easier as you aren't necessarily trying to center the click, the goal is just to guarantee that the cursor is always far enough in from the corner of the image so that it always hits the button.

**Comment by carloskpo10** [comment]
![image](https://user-images.githubusercontent.com/85960063/122114127-8d337a80-cde8-11eb-8a1a-c41b173cb2c5.png)

**Comment by Detergent13** [comment]
Definitely possible to do some quick math and just click at the centre of the image rather than the top corner. Would just be adding 1/2 of the width and height to the coordinates to click at.
