### ISSUE TITLE
Contributing to your project

### ISSUE THREAD

**Issue by zhaxxDev** [Detergent13/tft-bot#23]
Fixed the major problems I have been having from having the bot up for long periods of time which is unexpected ending and the bot doesn't know to reconnect or find next game. Works like a charm now for days straight with no issues. Would to have you add my code to the bot.

**Comment by Detergent13** [comment]
That's great to hear, thank you! I'd be happy to add your contribution, would you mind forking the project and then opening up a pull request for the changes?
