### ISSUE TITLE
Same resolution but doesn't work

### ISSUE THREAD

**Issue by hoongchuen96** [Detergent13/tft-bot#25]
Doesn't start queue when I pressed Ok after setup but cmd shows 'Bot started, queuing up!'. Tried manually queueing and accepting the game with the bot running but nothing happens in game either. Client resolution is set as 1280x720 and in game resolution is set as 1920x1080.
![image](https://user-images.githubusercontent.com/23335995/120873836-5c786780-c5d6-11eb-95f2-63e31d57920e.png)

**Comment by Detergent13** [comment]
Are you running the game in borderless mode? You might have to re-capture everything if that doesn't work out for you. Also, try running the script as an administrator- sometimes you need higher permissions to emulate mouse/keyboard input, which the script does.

**Comment by hoongchuen96** [comment]
Set game to borderless mode and ran the script as administrator, works in game now but still not working for the client. How do I re-capture the images of the client, do I just print screen and crop the buttons as image?

**Comment by hoongchuen96** [comment]
Everything works fine now, thank you. Re-captured the client buttons, set game to borderless mode and ran the script as administrator.

**Comment by hoongchuen96** [comment]
Everything works fine now, thank you. Re-captured the client buttons, set game to borderless mode and ran the script as administrator.
