### ISSUE TITLE
Doesn't enter new queue after finishing 1st game?

### ISSUE THREAD

**Issue by aaronwangy** [Detergent13/tft-bot#27]
Bot works on startup, buys champs, plays, etc, and surrenders correctly. When the game ends and returns to lobby, the bot says 'entering queue' but doesnt actually do anything. Launcher is correct size and game plays in borderless 1920x1080 windowed

**Comment by zhaxxDev** [comment]
Could be an issue with the capture of the play again button

**Comment by aaronwangy** [comment]
interesting, i've noticed my launcher is quite slow with returning to lobby after surrendering, could the lag delay here be an issue?

**Comment by Detergent13** [comment]
Your launcher definitely could be the issue- the script literally just waits 10 or so seconds (forget the actual number, but it's a fixed delay), then searches for the next capture.

Definitely not the best way to do it, but just was what I got working at the time of writing it. I would suggest experimenting with increasing that delay, and I'll also merge #28 just in case I'm overcomplicating things and it is just a capture issue.

**Comment by aaronwangy** [comment]
Actually just tested it with setting delay to 15, it recognizes 'Play again' button on the post game summary page, but after clicking it to return to the lobby, the mouse jumped to the top left corner of the computer monitor and clicked. This caused the game to go into background and whatever tab (Chrome) I had in the back was now brought to the front, causing bot to get stuck. Anyone else with this issue, or does this issue sound familiar?

**Comment by Detergent13** [comment]
Interesting, seems like you're making progress at least. Any chance there could be something weird with your monitor resolution being different than your League resolution, using multiple monitors, etc.?

I'd also try a reinstall of the modules, Python, etc. just in case. Can never hurt! 

My main thought at the moment would be that there might be something like I mentioned before interfering with the script, or another program that manages mouse input or uses its emulation that's getting in the way. So weird that it only happens at that stage of the script though. 

Worst case it might just work without having anything in the background (just minimise/close Chrome while using the script).

**Comment by Detergent13** [comment]
Could also be an issue with scanning or clicking too fast, really _shouldn't_ be though.
