### ISSUE TITLE
Need help with syntax Error

### ISSUE THREAD

**Issue by musyiir** [Detergent13/tft-bot#28]
printy(f"Welcome! You're running Detergent's TFT bot.\nPlease feel free to ask questions or contribute at https://github.com/Detergent13/tft-bot", "nB")
                                                                                                                                                    ^
SyntaxError: invalid syntax

thats the error showns

**Comment by musyiir** [comment]
i following all the requirment

**Comment by Detergent13** [comment]
This is a VERY weird issue if I'm understanding it correctly. Is the syntax error thrown right as the link begins? Just want to make sure that it's not a formatting thing with GitHub.

I'd highly recommend clearing your Python modules and re-installing all of the requirements as well. It's probably an issue with your Printy or maybe even Python installation.

**Comment by musyiir** [comment]
i rld install the printy, but it say this symbol --> " as a syntax error

**Comment by Detergent13** [comment]
Which quotation mark of the four? Also, try removing the `f` before the first `"`.

**Comment by musyiir** [comment]
well worked for now, after reisntal python xD, thanks for fast respond
