### ISSUE TITLE
bro look what i get

### ISSUE THREAD

**Issue by carloskpo10** [Detergent13/tft-bot#29]
![image](https://user-images.githubusercontent.com/85960063/122100686-0cb94d80-cdd9-11eb-8724-b14f3360af6d.png)

**Comment by Detergent13** [comment]
This is due to a version conflict, please uninstall your modules and install the requirements.txt again.

**Comment by carloskpo10** [comment]
![image](https://user-images.githubusercontent.com/85960063/122488420-0d9ddb00-cfa3-11eb-9123-38c966a74538.png)
hand I already corrected it but now it does nothing, it just shows and stays still, it takes almost 7 hours to do it, I left it all night and it has not started any

**Comment by Detergent13** [comment]
Try running the script as administrator please!

**Comment by zhaxxDev** [comment]
Bro look at the language, mate you need to recapture everything.
