### ISSUE TITLE
Don't know how to install it

### ISSUE THREAD

**Issue by axoee** [Detergent13/tft-bot#30]
Could someone add my discord and tell me how im supposed to install the requirements? I haven't a clue on how this is supposed to be done. It just opens the .txt file and nothing happens when I open up the tft python file. My discord is Space#8575

**Comment by Detergent13** [comment]
Please read the installation instructions on the homepage of the repo, both of those questions are answered.

**Comment by carloskpo10** [comment]
ami demora para poder hacer un paseo literal 8 horas y ni una partida cuando arrancara su bot
