### ISSUE TITLE
Props + questions about termination

### ISSUE THREAD

**Issue by wedftyweb** [Detergent13/tft-bot#33]
Hey great script! This was something I'd tried to do in autohotkey unsuccessfully. I put an iteration counter in the printout so you can tell at a glance how many games were run. What do you do to terminate it early? I thought maybe control-c (or d or z) but its not the cmd window thats active. My league window seems to not allow alt-tabbing to other windows which could just be a personal or fullscreen issue; but i'm having to alt-tab, then win key, then close the cmd from taskbar.

Some less important things that I've wondered; how and when is it choosing to reroll? Were the champs it buys selected because the image recognition works best on them, or just often available?

Thank you again for your work! This has gotten me past a serious stumbling block and inspired me to keep working on it.

**Comment by Detergent13** [comment]
Hey! Thanks so much for getting in touch, happy to be of help. 

Personally I alt+tab to the script then alt+f4 super quickly- definitely not the most elegant solution but it works. Almost certainly would have to be in borderless windowed for that to work though, so maybe a key interrupt or something would be handy. I don't have any experience with anything like that personally, but I'm sure it's possible some way!

The bot builds a mainly Hellion comp which (I'm told at least- I don't actually play TFT myself) is known for being strong and easy to get early game, which is most of what the bot is playing. Any unit should work though, I'd say pretty much equally well unless you'd need to increase the confidence factor a bit for some reason. (Like if a champ could be confused for a button for some reason, which I doubt, but could happen)

Thanks again for your kind words, and feel free to open up a PR if you do happen to add any features or an issue if I can help answer any more questions!
