### ISSUE TITLE
Program will not continue passed the initial Que up

### ISSUE THREAD

**Issue by thd13002** [Detergent13/tft-bot#35]
the code will que up, and then accept. however, it does not jump to loading, or ready to play. it just stops working for me after this point. 

![image](https://user-images.githubusercontent.com/14093576/123298232-49c2c580-d4e6-11eb-82a1-1717c855b8e1.png)

**Comment by Detergent13** [comment]
From the troubleshooting steps:

"The bot is configured to work with in-game resolution 1920x1080, and League client resolution 1280x720. You can switch this up though, just re-capture the images in the captures folder!"
