### ISSUE TITLE
bot is stuck at "Bot started, queuing up!" step does nothing in game

### ISSUE THREAD

**Issue by miksvell** [Detergent13/tft-bot#36]
I have problem of being stuck here on the bot. When i press Ok on im in lobby it press find match and accept but then the bot is stuck on this step and it doesnt do anything in game i have right resolution in launcher and in game so i dont understand what am i doing wrong
![stiahnuť](https://user-images.githubusercontent.com/76617071/123520712-3f552700-d6b2-11eb-9b01-779df57464ca.png)

**Comment by Detergent13** [comment]
Try running the script as administrator please!
