### ISSUE TITLE
I cant install pip

### ISSUE THREAD

**Issue by frapz9** [Detergent13/tft-bot#37]
![Screenshot_1](https://user-images.githubusercontent.com/86545525/123533774-91b43900-d6ee-11eb-80a6-ce125a79545e.png)

**Comment by Detergent13** [comment]
You need to cd to the directory that it's downloaded in.

With all due respect, this isn't an issue with my code/project- in the future, please direct general command prompt/pip/Python questions to their respective resources.

Thank you.
