### ISSUE TITLE
Can you get banned for this?

### ISSUE THREAD

**Issue by WilliamEmami** [Detergent13/tft-bot#38]
Basically title, if I leave this on for 10 hours/day (during work) sporadically (not every day, maybe like every 3rd day). I really want to the end of the battle pass but unfortunately I don't have time. I don't really care about winning anyways, but I'm not sure how riot feels on bots that just run it down in TFT, opposed to bots in TFT that try to win.

**Comment by Detergent13** [comment]
#34, please check previous issues before opening your own, thanks!
