### ISSUE TITLE
Bot doesnt click ok button for missions,

### ISSUE THREAD

**Issue by zhaxxDev** [Detergent13/tft-bot#40]
WTF???? I went over the code literally nothing should have changed right? I also recaptured the button... What happened????????????

**Comment by Detergent13** [comment]
Are you running the script as administrator? Very odd that it'd randomly change though.

**Comment by zhaxxDev** [comment]
> Are you running the script as administrator? Very odd that it'd randomly change though.

I'm running CMD as admin yes

**Comment by Detergent13** [comment]
Try uninstalling and reinstalling the required modules and/or Python- there's a chance that one of those is corrupted or somehow broke.

**Comment by Detergent13** [comment]
Any update?

**Comment by zhaxxDev** [comment]
I think I finished all the missions so I havent been able to test again, I will reopen if this happens again.
