### ISSUE TITLE
Bot does not queue up

### ISSUE THREAD

**Issue by dlipka00** [Detergent13/tft-bot#42]
Hi, I've followed the troubleshooting guide and checked the closed issues. I have my league client open in a TFT lobby, I click OK on the pop up for the script, and then nothing happens. I have to CTRL+C to end the script because it doesn't do anything.

Any ideas? Thanks

**Comment by Detergent13** [comment]
Hi, thank you first of all for looking through troubleshooting and closed issues! 

Sorry if you've already tried, but are you running the script as administrator?

**Comment by dlipka00** [comment]
Yes, I run as administrator. The message in the command prompt never changes from the queueing up message.

**Comment by Detergent13** [comment]
#43 might be worth a look as well!

**Comment by dlipka00** [comment]
Would this be the image for the lobby then? When I start the bot, it just sits in the lobby and never searches. Would like to hear your suggestions on what to change.

Thanks!

**Comment by Detergent13** [comment]
Seems like it! Looks like somebody has included the proper image for it in #44, so feel free to use that or just re-capture it yourself. The change should be pushed as soon as there's a pull request for it. Let me know how that goes for you!

**Comment by dlipka00** [comment]
Seems to be that fixed the issue. Thank you!
