### ISSUE TITLE
doesnt work after accepting match

### ISSUE THREAD

**Issue by nahid-ni1609698** [Detergent13/tft-bot#43]
Hi, the bot doesnt go past the accpet phase and gets stuck on "queuing up"

**Comment by Detergent13** [comment]
Please read the troubleshooting guide and closed issues first. Re-open if none of those solve it, but I can almost guarantee that they will.

**Comment by nahid-ni1609698** [comment]
the issue was they updated the loading screen background so just needed to change the loading image to the latest one, thanks tho

**Comment by Detergent13** [comment]
Interesting! Thanks for the update, and sorry to assume.
