### ISSUE TITLE
Updating Bot

### ISSUE THREAD

**Issue by PsychoticDragan** [Detergent13/tft-bot#44]
Hey with this new patch the loading screen has changed. I have additions to make the code a little cleaner and added a few extra lines to prevent downtime with the bot. If you would like to know more let me know. I don't know how pull-requests work So i'm presenting this as an issue here. Here's a new loading.png either way.

![loading](https://user-images.githubusercontent.com/85346858/126551518-288d950e-08ec-428f-96d0-5128608794b5.PNG)

**Comment by Detergent13** [comment]
Hey! So how pull requests work is that you just fork this repository, push your changes to that fork, and then create a pull request, which I'll then review and hopefully merge.

I could in theory just add that image, but I wouldn't want to take credit for your work if at all possible! I'd also be interested to see your stability fixes.

Thanks for your help!

**Comment by PsychoticDragan** [comment]
That makes sense. I'm more so confused on how i would open the pull request. I click create then it just like says main pointing to main. I don't know how to submit something for said request.

**Comment by PsychoticDragan** [comment]
I think I basically figured it out for the basic concept, but might have to submit it differently for the code? Let me know.
