### ISSUE TITLE
I keep getting SyntaxError:invalid when I try to input anything

### ISSUE THREAD

**Issue by kooookies** [Detergent13/tft-bot#49]
Could you please leave more detailed instructions, I have no clue what I am doing.

Thanks

**Comment by kizxlove** [comment]
Can you provide some images?

**Comment by Detergent13** [comment]
Agreed, please include images or a more detailed description of the issue. What are you trying to input and how?

**Comment by Detergent13** [comment]
Closing since author seems to be inactive. Please re-open if you still need help.
