### ISSUE TITLE
ScreenShot has no Attribute

### ISSUE THREAD

**Issue by sharjeelarif010321** [Detergent13/tft-bot#51]
Hi, I keep getting this error when I try to run the script.
Traceback (most recent call last):
  File "tft.py", line 203, in <module>
    queue()
  File "tft.py", line 65, in queue
    if onscreen("./captures/tft logo.png"):
  File "tft.py", line 24, in onscreen
    return search(path, precision)[0] != -1
  File "/Users/sharjeelarif/opt/anaconda3/lib/python3.8/site-packages/python_imagesearch/imagesearch.py", line 120, in imagesearch
    im.thumbnail((round(im.size[0] * 0.5), round(im.size[1] * 0.5)))
AttributeError: 'ScreenShot' object has no attribute 'thumbnail'

I'm running this on MacOS

**Comment by Detergent13** [comment]
Hey! This is almost certainly caused by either the wrong version or a corrupt version of OpenCV and/or ImageSearch. Please try completely uninstalling and reinstalling both!

**Comment by sharjeelarif010321** [comment]
Yup got it working but now the bot is stuck at queuing up and nothing after that. The terminal has full accessibility permissions and the script is being run as admin using sudo. Do you know any reason why this is happening? I checked previous closed issues but no solution seems to resolve my problem.

**Comment by Detergent13** [comment]
Re-capture the accept button!

**Comment by sharjeelarif010321** [comment]
I can't seem to get the bot to accept the accept dialogue. I've updated the accept.png screenshot.

**Comment by Detergent13** [comment]
Maybe decrease the confidence for the accept clicking? And does the mouse go to the button and not click, or just does nothing when it pops up?
