### ISSUE TITLE
Not working sometimes 

### ISSUE THREAD

**Issue by Zaphyria** [Detergent13/tft-bot#56]
I've noticed that the bot sometimes stops working during the queueing process - such as not clicking on find match. Usually occurs after I've run it for 8+ hours. Is this intentional?

**Comment by Detergent13** [comment]
Nope, this isn't intended behaviour! I'd recommend re-capturing the relevant buttons, since this is probably a result of the script either missing the button, or thinking it's on a different step than it actually is.
