### ISSUE TITLE
Script runs, I click yes for script to run automatically, and then the box disappears and nothing happens

### ISSUE THREAD

**Issue by BibleBeltBronze** [Detergent13/tft-bot#57]
The script runs and the pop up box shows up. I click yes and then the box disappears and nothing happens. Please help!

**Comment by BibleBeltBronze** [comment]
When I open the main it pops up, but when I press ok when I am in the TFT lobby it disappears. Is there a way for me to run it as administrator even though it is a python file?

**Comment by BibleBeltBronze** [comment]
This one was with administrator. Forgot to do that with the previous. 
<img width="973" alt="oops" src="https://user-images.githubusercontent.com/92081926/136493563-3072dc6c-bc0c-4bf3-83ea-28c1cd9b9804.PNG">

**Comment by Detergent13** [comment]
Sorry, forgot to mention that you should be navigating, or cd'ing to the folder that the file is in first.

So your batch file should actually be something like this:

`cd C:\Users\<yourname>\Downloads\tft-bot`
`py tft.py`
`pause`

But adjust to wherever the tft.py file actually is.

**Comment by Detergent13** [comment]
It's not detecting that you've ended the match one way or another- does it properly surrender?

**Comment by Detergent13** [comment]
Have you been giving it time to press play again? Keep in mind that the script has delays in it, so it will appear to not be doing anything for some time (around 15 seconds I believe?)

If you have been giving it time, this might be an issue we with either your game closing too fast for the script to realise that the game is actually over, or your game taking too long to end and return to the client, thus trying to press play again before it's on screen.

Either way, I'd suggest adding some more print statements at each stage of the script to get a better idea of exactly where things are going wrong.

**Comment by Detergent13** [comment]
Glad to hear it, enjoy!
