### ISSUE TITLE
bot gets stuck when game is lost

### ISSUE THREAD

**Issue by vsnrytune** [Detergent13/tft-bot#64]
Works fine, until you finish in 8th place, then it just gets stuck on the screen that has two buttons saying "Exit Now" or "Keep Watching"...

Also is there a way to make it surrender at exactly 15 or 20 minutes in? As surrendering at 6-6 takes too long, anywhere from 20 to 30 minutes which is not what I want

**Comment by Detergent13** [comment]
Probably best to re-capture `dead.png`. This case is covered for, but probably just an issue with the capture not matching for you. There is a line in the code where you can change when you surrender- just change it to a capture of whichever stage you want to surrender at! (Should be commented)

**Comment by vsnrytune** [comment]
> Probably best to re-capture `dead.png`. This case is covered for, but probably just an issue with the capture not matching for you. There is a line in the code where you can change when you surrender- just change it to a capture of whichever stage you want to surrender at! (Should be commented)

hi i found out the issue was caused by the new tft update, i had to update loading.png and all champion png's, also replace kled, kennen and vlad with different champs as they're no longer in the game

**Comment by Detergent13** [comment]
You could also just pull the current branch- the script is already updated to the new set!
