### ISSUE TITLE
bot opened start menu

### ISSUE THREAD

**Issue by vsnrytune** [Detergent13/tft-bot#66]
It was running just fine for about 7 hours and I just found it idling in the after game screen with my start menu open. I wasn't anywhere near my pc to press the windows button so the bot must've done it (it was also not pressing "Play Again" even though it was visible on the screen). I'm not sure what caused this, any idea?

**Comment by Detergent13** [comment]
Probably a capture that's mistaking your Windows button for something else that the script tries to click on. Sadly it's near impossible to figure out which one is causing the issue unless you happen to see it or at least know what stage it's on, but you could always just try cranking up the precision for the onscreen() calls! Probably one of the smaller captures if I had to guess, maybe the new Chemtech and Scrap ones?

**Comment by Detergent13** [comment]
Closing since the author seems to be inactive. Please re-open if you still need help!
