### ISSUE TITLE
Trying to reroll / buy on grey (aka out of money) + bench full

### ISSUE THREAD

**Issue by Raenef** [Detergent13/tft-bot#72]
First thank you,

i recognized 2 issues:

1. he seems to like to try to buy and/or reroll when he is out of money (0g)
- as in clicking on the greyed out „reroll“ or champion icons repeatively trying to buy them but not having gold to,still trying to though
- as there is no animation for reroll button clicking itself that part is an assumption

2. „same“ trying to buy issue if he has gold buy the bench is full

**Comment by CaS1ow** [comment]
it's not an error, you can capture the greyed out section and then add some code 
ex)
while not onscreen("./captures/greyed reroll.png")
    click_to("./captures/reroll.png")

I wanted to tell you. This is not an error and it is not necessary
But it seems necessary for the program to work more precisely :D

**Comment by Detergent13** [comment]
Just to add- if my memory serves me correctly, this Imagesearch library (or OpenCV?) only uses the grayscale image. So, the colour version and grayscale version (or tinted version) will effectively be the same to the computer. It's a bit of a weird side effect, but not unexpected behaviour. 

It's definitely wasteful to reroll on a full bench, but it would be quite the task to scan every bench spot and get it accurately.

**Comment by Raenef** [comment]
yes, my tries worked out that it ignores color, did some short tries on the 10er gold markers on the left but didnt work so far as a "stop" signal
