### ISSUE TITLE
Finishing a lunar mission stops the bot

### ISSUE THREAD

**Issue by Raenef** [Detergent13/tft-bot#77]
Hi,

already had it a multible times, but for me it stops working after it finishes a lunar quest:

![1](https://user-images.githubusercontent.com/89660477/152647004-99ec17af-6833-4526-b464-9bed4ef50fa4.PNG)

It does not jump back to the after game screen...
if you manually click ok it starts working again

doesnt seem to get pressed:
![2](https://user-images.githubusercontent.com/89660477/152647002-4d590019-3c54-4a5c-9ae2-ee05e4e0be00.PNG)

**Comment by Detergent13** [comment]
Recapture your `missions ok.png`!

**Comment by Raenef** [comment]
tx gonna try it
