### ISSUE TITLE
The bot do not work

### ISSUE THREAD

**Issue by Illia-Shiba** [Detergent13/tft-bot#78]
I downloaded the files on disk C. After that, I installed the requirements, opened the LOL client, ran the TFT script. I pressed the "OK" button in the lobby, but nothing happened. 
All that I see is only that bot started and queuing up. But that's all.
What did I do wrong if all instructions were done? 
![Screenshot_1](https://user-images.githubusercontent.com/59292631/154017652-98d11def-5c57-44df-b6e8-22fbe720acab.png)

**Comment by Detergent13** [comment]
Try running as administrator maybe?

**Comment by Detergent13** [comment]
Interesting. Are you on the right resolution? If so, try recapturing the TFT logo and find match button

**Comment by liquidbunx** [comment]
Adding on to the comment regarding having the right resolution, you need to make sure that your windows resolution is at 100%, otherwise it will not work and you have to recapture the images again. So unless you want to recapture, go to your windows resolution (scale and layout) and change it to "100% (Recommended)".

**Comment by Detergent13** [comment]
> Adding on to the comment regarding having the right resolution, you need to make sure that your Windows resolution is at 100%, otherwise it will not work and you have to recapture the images again. So unless you want to recapture, go to your Windows resolution (scale and layout) and change it to "100% (Recommended)".

Thanks for adding that! Didn't realise that could cause issues.

**Comment by Illia-Shiba** [comment]
Sorry, I had not got the PC the last two days, so I did not try it for TFT season 6. But I saw that my resolution really was 125%,  I thought I fixed that. Probably it was the true problem. 
Hope that your bot will support the next season too)
