### ISSUE TITLE
6.5 Bot Loading PNG Broken + solution

### ISSUE THREAD

**Issue by Raenef** [Detergent13/tft-bot#79]
Good morning,

as "loading" is not printed be the loading icon which seems to be taken from the background picture.
i captured a flower (pic below) and it works again

```
# Start main process
def queue():
    if onscreen("./captures/tft logo.png"):
        click_to("./captures/find match ready.png")      
    while not onscreen("./captures/loading.png"):
        time.sleep(1)
        click_to("./captures/accept.png")

    print("Loading!")
    loading()
```

![loading](https://user-images.githubusercontent.com/89660477/154233132-3c5c9e4c-0af0-4db5-8d9f-52347ad10d74.PNG)

**Comment by MrIslamAIman** [comment]
that fix my problem ty =D

**Comment by Detergent13** [comment]
Implemented, thank you!

In the future, feel free to implement these changes through a pull request; it's quicker and means you get credit too ;)
