### ISSUE TITLE
Bot stops working after level up

### ISSUE THREAD

**Issue by lunesco** [Detergent13/tft-bot#81]
As in the title

**Comment by Detergent13** [comment]
Do you mean leveling up in TFT or your account leveling up?

**Comment by lunesco** [comment]
Yes, in TFT, but I tested this app a lil bit more and it happenned only once, so i downt know if it is actually the issue

**Comment by Detergent13** [comment]
Almost certainly not the root issue then. The bot doesn't respond to leveling up, and I don't see any reason why it'd obstruct the script. Let me know if you find the root reason though!

**Comment by Raenef** [comment]
i have a "similar" event:

`print("Looks like the match is over! Re-queuing")`

appears in the command window

**Comment by Raenef** [comment]
did a test:

command window:
```
test: fail dead
Looks like the match is over! Re-queuing
```

code:
```
    if onscreen("./captures/play again.png"):
        print("test: fail play again")  #error test
        won_match()
    if onscreen("./captures/3-4.PNG"):  # check for loss
        click_to("./captures/dead.PNG") #error test
        print("test: fail dead")
        won_match()
```

but i see no reason why if sees the dead

**Comment by Raenef** [comment]
ok, i think i find out my problem, i might have f**ed it up, brb
