### ISSUE TITLE
Anima Squad 2022 - League of Legends

### ISSUE THREAD

**Issue by MrIslamAIman** [Detergent13/tft-bot#85]
it is not a problem in the code or the bot itself 
but with the new system of the token bank ( 200 points from time spent playing ) 
the bot is not effective as the last event 
so I just want to know what changes can I make to your bot to make it more effective? 
if I make the game longer would it help? ( i tried to change ur line of code to make the bot ff at 5-1 but it crash for some reason)

anyway just want to ( brainstorm ) with you guys about how can I make more from the bot =D

**Comment by Detergent13** [comment]
You know that if you change that line you need to have to make your own screenshot for that stage, right?

**Comment by MrIslamAIman** [comment]
yeah sure =D iam new at programing but i understand the basics of image recognition =D 
I do I got a screenshot to the lvl but i didn't read ur comment till the end XD my bad 
*also the image recognition struggles with 5 being it sees it as 3 so I had to do 6 as that's seen as a 5*

but still in ur opinion is it better to make it longer or just as it is?

**Comment by Detergent13** [comment]
Ah yeah, that makes sense. I think the best way to fix this would be to change onscreen()'s method signature to pass in a confidence interval, then crank that up past its current default. Or as you found, a different stage works too!

**Comment by MrIslamAIman** [comment]
=D thanks man
