### ISSUE TITLE
[Request] Can be adapted to farm LoR

### ISSUE THREAD

**Issue by Benjamin-Berger** [Detergent13/tft-bot#9]
Legends of Runeterra is a lot more intricate (at least in terms of how the mouse moves) but I think this can be adapted for it. 

You would be able to grind xp daily by surrendering to AI and vs players. you can get a capped amount of xp daily with this.
Like TFT, after awhile of surrenders, Riot puts you in a queue of other surrender bots. With some more advanced logic tweaks, this could be programmed to take advantage of them.

For instance, many of the bots you find will try and stall out the game. By not surrendering often times the opponent bot will surrender if they think its a lost cause. Unlike griding tokens in tft, after enough losses you wont get any exp in LOR, only for wins. 

I don't have time for awhile but hopefully in a couple months I'll attempt to work on this.

**Comment by Detergent13** [comment]
Definitely could work, I'd be interested to see it working. Probably won't work on it myself in all honesty, but you absolutely have my blessing to adapt the code for it.

**Comment by Benjamin-Berger** [comment]
When I finish my current project I'll definitely make an attempt at this! Thanks for your approval!
