### ISSUE TITLE
Sometimes my client go back to Quick Play and not lobby

### ISSUE THREAD

**Issue by revhellyon** [Detergent13/tft-bot#94]
After 2~3 matches, my client go to this https://i.imgur.com/972r0uE.jpg and not the lobby then the bot gets stuck unable to queue again

**Comment by mallkorebit** [comment]
have you solved the problem?

**Comment by revhellyon** [comment]
No

**Comment by mallkorebit** [comment]
I fixed this by automatically closing the client every game

**Comment by Detergent13** [comment]
Ah. Good to know. Yeah the source is definitely because of a Riot issue, but it'd be pretty easy to add a check for it if I get around to it. Just click the "Lobby" button after hitting "Play Again."
