### ISSUE TITLE
"ModuleNotFoundError: No module named 'keyboard'" error 

### ISSUE THREAD

**Issue by enzomartins** [Detergent13/tft-bot#98]
![image](https://user-images.githubusercontent.com/45863649/198848113-0f74830d-dca7-4821-a0ec-5b0f947439ba.png)
 
I'm getting this "ModuleNotFoundError: No module named 'keyboard'" error when trying to insert the "py tft.py" or "tft.py" command lines.

**Comment by Kyrluckechuck** [comment]
What branch are you trying to run? By the looks of it, line 3 of this repo doesn't use `keyboard` at all
