### ISSUE TITLE
I can't properly run "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by enzomartins** [Detergent13/tft-bot#99]
Whenever I try to run the install requirements command line, I get a 390 lines error.
![image](https://user-images.githubusercontent.com/45863649/200211648-8ae01ad8-187e-4903-8ea8-b3a936ac3ad5.png)
![image](https://user-images.githubusercontent.com/45863649/200211654-ceabfa23-2331-4e07-a548-b5cde5f05cb0.png)
![image](https://user-images.githubusercontent.com/45863649/200211663-e5877138-8b72-4e57-981a-d42c8cb23b3d.png)
![image](https://user-images.githubusercontent.com/45863649/200211668-b243b12b-336e-48a1-9dd1-aeaee94a7609.png)
![image](https://user-images.githubusercontent.com/45863649/200211672-0dad4d6a-b35a-4161-b770-051ad1916234.png)
![image](https://user-images.githubusercontent.com/45863649/200211679-76cb6394-6e9d-4437-90c8-df08d0006879.png)

**Comment by Detergent13** [comment]
What's your python version? It seems like pip is complaining about you having the wrong one. Just want to confirm my suspicions.

`py -V`

**Comment by enzomartins** [comment]
Version  3.11.0
![image](https://user-images.githubusercontent.com/45863649/200212335-849a2f39-dce9-4d20-8b80-3509524e254f.png)

**Comment by Detergent13** [comment]
Makes sense... please run with Python 3.8.3 as the readme asks
